import Head from 'next/head'
import Image from 'next/image'

export default function Home() { 
  return(
    <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="Hexabase-Fabicon.png" />
        </Head>
        <main className="main">
            <div className='main-form'>
                <div className='header'>
                    <Image
                    src="#"
                    alt="copany-Logo"
                    className="Top_Logo"
                    width={350}
                    height={120}
                    priority
                    />
                    <p>以下のフォームより、お気軽にお問い合わせください。<br />お仕事のご依頼やご相談については、後日担当者よりご返信します。</p>
                </div>
                <div id='page1'>
                    <p className='fast-navi'>1,ご入力</p>
                    <p className='second-navi'>2,送信完了</p>
                </div>
            </div>
            
            <div className='contact-form'>
                <form>
                    <div id='top' className='form-grupe'>
                        <div className='label'>
                            <label htmlFor="name">
                            氏名
                            </label>
                            <p className='required'>
                            必須
                            </p>
                        </div>
                        <input 
                        name='name'
                        type="text" 
                        className='text01'
                        required
                        />
                    </div>
                    <div className='form-grupe'>
                        <div className='label'>
                            <label htmlFor="Furigana">
                            ふりがな
                            </label>
                            <p className='required'>
                            必須
                            </p>
                        </div>
                        <input 
                        name='Furigana'
                        type="text" 
                        className='text01'
                        required
                        />
                    </div> 
                    <div className='form-grupe'>
                        <div className='label'>
                            <label htmlFor="Company">
                            会社名
                            </label>
                            <p className='required'>
                            必須
                            </p>
                        </div>
                        <input 
                        name='Company'
                        type="text" 
                        className='text01'
                        required
                        />
                    </div>
                    <div className='form-grupe'>
                        <div className='label'>
                            <label htmlFor="Email">
                            E-Mail
                            </label>
                            <p className='required'>
                            必須
                            </p>
                        </div>
                        <input 
                        name='Email'
                        type="text" 
                        className='text01'
                        required
                        />
                    </div>
                    <div className='form-grupe'>
                        <div className='label'>
                            <label htmlFor="Contact-text">
                            ご相談内容
                            </label>
                            <p className='required'>
                            必須
                            </p>
                        </div>
                        <textarea 
                        className='text02'  
                        name='Contact-text' 
                        required />
                    </div>
                    <div className='form-grupe'>
                        <label>
                            <input 
                            className='chbox' 
                            type="checkbox" 
                            required />
                            <a 
                            id='text' 
                            href="#"
                            >
                            プライバシーポリシー
                            </a>
                            に同意する。
                        </label>
                    </div> 
                    <div className='bottun'>
                        <button type="button"><a href='/contact-end'>送信</a></button>
                    </div>
                </form>
            </div>
        </main>
    </>
  )
}
